--- # CRON MODULE EXAMPLE

- hosts: apacheweb
  user: test
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add a cron job to the test User
      cron: name="list files" minute="0" hour="1" job="ls -al > /home/test/cronresult.log"
       
