--- # Deletgate to function demo

- hosts: apacheweb
  sudo: yes
  user: test
  gather_facts: yes
  connection: ssh
  tasks: 
  - name: Run a remote ping on the application server
    command: ping -c 4 odania3 > /home/test/Playbooks/ping.out
    delegate_to: 127.0.0.1
  - name: Install a package
    yum: pkg=lynx state=latest


